version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: Asia/Tokyo
    commit-message:
      prefix: "ci:"
    cooldown:
      default-days: 7

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: Asia/Tokyo
    commit-message:
      prefix: "go:"
    cooldown:
      default-days: 7
