changelog:
  exclude:
    labels:
      - tagpr
  categories:
    - title: 💥 Breaking Changes
      labels:
        - sacloud-major
    - title: 🚀 New Features
      labels:
        - sacloud-minor
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: 📦 Dependency Updates
      labels:
        - dependencies
